version: "3.9"

services:
  app:
    build:
      context: .
      args:
      - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}/volumes/.data:/var/lib/postgresql/data
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file: ${PWD}/.envs/.prod/.postgres
    depends_on:
      - db


  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/volumes/app:/app
    env_file: ${PWD}/.envs/.prod/.postgres


volumes:
  dev-db-data:
  dev-static-data: